# Generated by Django 4.0 on 2022-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('qua', models.IntegerField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
