# Generated by Django 4.0 on 2022-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_docreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreg',
            name='qua',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
