# Generated by Django 4.0 on 2022-07-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0004_alter_docreg_qua_alter_userreg_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docreg',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='gender',
        ),
    ]
