# Generated by Django 4.0 on 2022-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0005_remove_docreg_gender_remove_userreg_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='labsadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('drname', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('bgroup', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
