# Generated by Django 4.0 on 2022-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0006_labsadd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='labsadd',
            new_name='labsaddreport',
        ),
    ]
